[2013-01-27 19:48:07,699][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x1610d029, /192.168.2.13:57881 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,700][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x8b6dffbc, /192.168.2.13:57875 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,700][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x140a16da, /192.168.2.13:57881 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,700][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x332e94f2, /192.168.2.13:57880 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,700][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x4f4b1ff2, /192.168.2.13:57875 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,700][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x07a81451, /192.168.2.13:57880 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,700][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x200cea32, /192.168.2.13:57882 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,699][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x1d775deb, /192.168.2.13:57874 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,761][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x30a8c540, /192.168.2.13:57879 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,779][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x799c9817, /192.168.2.13:57879 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,782][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x6d7b74b3, /192.168.2.13:57876 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,783][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x650bd474, /192.168.2.13:57877 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,786][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xb7da5608, /192.168.2.13:57878 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:48:07,789][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xa55f64a9, /192.168.2.13:57882 => /192.168.2.13:9300]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 19:51:58,100][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 19:55:58,466][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 19:59:58,765][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 20:03:59,089][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 20:07:59,391][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 20:11:59,688][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 20:15:59,993][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:07:00,076][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xcc596d47]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,077][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x98b0034a]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,079][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xcc87156c]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,080][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x5bc75d18]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,081][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x095aaf0b]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,082][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x5140393c]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,083][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x5b120907]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,084][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xc59c39a0]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:07:00,085][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x5f689040]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:658)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 22:08:20,188][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:12:20,594][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:16:20,888][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:20:21,189][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:24:21,654][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:28:21,989][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:32:22,292][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:36:22,591][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:40:22,889][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:44:23,253][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:48:23,656][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:52:23,952][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 22:56:24,288][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:00:24,687][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:04:25,101][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:08:25,450][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:20:26,709][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xd767de51]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,710][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x64208f84]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,711][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xccd6385e]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,712][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xef7f67a4]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,713][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x391319fc]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,714][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x57f1a4c1]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,715][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x8f8366f5]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,715][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xb994fe43]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,716][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x8ef68a60]], closing connection
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:658)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-27 23:20:26,717][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	... 7 more
[2013-01-27 23:24:27,058][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:28:27,358][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:32:27,649][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:36:27,989][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:40:28,288][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:44:28,685][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:48:28,987][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:52:29,460][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-27 23:56:29,794][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
